// const wrapError = (req, res, func) => {
//     try {
//         func(req, res);
//     } catch (err) {
//         console.error(err);
//         res.status(500).send('Something went wrong');
//     }
// };
